#AUTOGENERATED! DO NOT EDIT! File to edit: dev/05_activations.ipynb (unless otherwise specified).

__all__ = ['mish']

#Cell
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model
import tensorflow.keras.backend as K

#Cell
def mish(x):
    """Mish: A Self Regularized Non-Monotonic Neural Activation Function

    https://arxiv.org/pdf/1908.08681v1.pdf

    Parameters
    ----------
    x: tf.Tensor[float]
        Input tensor.

    Returns
    -------
    tf.Tensor[float]: Tensor of same shape as input x.
    """
    return x * K.tanh(K.softplus(x))